<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="icons8-ведро-краски-50.png" />
    <None Remove="man_13305169.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="icons8-ведро-краски-50.png" />
    <Resource Include="man_13305169.png" />
  </ItemGroup>

</Project>
